spring:
  datasource:
    # 数据库访问配置
    url: jdbc:mysql://123.60.222.104:6033/cn_20230223?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # mysql用户名
    username: root
    # mysql密码
    password: tianwanggaidihu
    # 下面为连接池的补充设置，应用到上面所有数据源中
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 50000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  type-aliases-package: com.bbs.*
  mapper-locations: classpath:/mapper/business/*.xml
  global-config:
    field-strategy: 0
    db-config:
      id-type: auto
      # 那个字段是逻辑删除字段，也可以在字段上添加注解@TableLogic，在这里边配置是全局生效
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
